version: '3.1'

services:
  prometheus:
    image: prom/prometheus:v2.0.0

    ports:
      - 9090:9090

    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    
  alertmanager:
    image: prom/alertmanager:v0.12.0

    ports:
      - 9093:9093
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana:7.2.1

    ports:
      - 3000:3000
    restart: unless-stopped

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.10.0
    ports:
      - 9300:9300
      - 9115:9115
    volumes:
      - ./config/blackboxexporter.yml:/etc/blackboxexporter/blackboxexporter.yml
    restart: unless-stopped  