version: '3.1'

services:
  prometheus:
    image: prom/prometheus:v2.0.0

    ports:
      - 9090:9090
    restart: always
    
  alertmanager:
    image: prom/alertmanager:v0.12.0

    ports:
      - 9093:9093
    restart: always
    
  grafana:
    image: grafana/grafana:5.4.2

    ports:
      - 3000:3000
    restart: unless-stopped

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.10.0
    ports:
      - 9300:9300
      - 9115:9115
    restart: unless-stopped